baseURL = "https://andre.arko.net/"
languageCode = "en-us"
title = "André.Arko.net"

[Taxonomies]

[permalinks]
post = "/:year/:month/:day/:slug/"
page = "/:slugorcontentbasename/"

[markup.goldmark.renderer]
unsafe = true

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[module.hugoVersion]
extended = false
min = "0.116.0"

[outputFormats.Atom]
name = "Atom"
mediaType = "application/atom+xml"
baseName = "atom"
isPlainText = false
rel = "alternate"
isHTML = false
noUgly = true
permalinkable = false

[outputs]
home = ["HTML", "RSS", "ATOM"]

[params.social]
twitter = "indirect"
